version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: edugrade_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:5
    container_name: edugrade_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data

  cassandra:
    image: cassandra:4
    container_name: edugrade_cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

  redis:
    image: redis:7
    container_name: edugrade_redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: edugrade_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - neo4j
      - cassandra
      - redis
    environment:
      - MONGO_HOST=mongo
      - CASSANDRA_HOST=cassandra
      - REDIS_HOST=redis
      - NEO4J_HOST=neo4j
    restart: always

volumes:
  mongo_data:
  neo4j_data:
  cassandra_data: